### ISSUE TITLE
请问作者，这个机器人是否可以下载源码给自己的小群使用

### ISSUE THREAD

**Issue by Tsurumaki-Kokoro** [Diving-Fish/Chiyuki-Bot#2]
看到空间上面说不要拉小群，想下载源代码自己搭建
在自己尝试的时候遇到了一些问题，maidx的部分指令不能用（分数线不能用，但是查歌曲别称的功能是正常的），请问是否需要什么别的依赖库

**Comment by Diving-Fish** [comment]
草这边的issue我都没有注意。看看mai-bot项目吧233
